config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
  resources :comments
end
 get '/pages/about' => 'pages#about', as: :about
 get "/pages/contact" => "pages#contact", as: :contact

 #get '/posts' => 'posts#index', as: :posts
 #post '/posts' => 'posts#create'
 #get "/post/:id" => "posts#show", as: :post

 #patch "/post/:id" => "posts#update"
 #delete "/post/:id" => "posts#destroy"
 #get '/posts/new' => 'posts#new', as: :new_post

 #get "/post/:id/edit" => "posts#edit", as: :edit_post

 root 'posts#index'

 


 
end








 

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

	
	  validates :title, presence: true
	  validates :body, presence: true
	  validates :title, length: { minimum: 5 }
	  validates :body, length: { minimum: 20 }

	  
	  belongs_to :user
	  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #before_save :encrypt_password
  has_many :posts      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		flash[:notice] = "You roll"
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		flash[:notice] = "You Got Rid Of It"
		redirect_to post_path(@post)
	end

	private
	#def find_post
		#@post = Post.find(params[:id])
		
	#end
	def comment_params
		params.require(:comment).permit(:name, :body)
		
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		
		

	end

	def contact
		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	
	def index
		@posts = Post.all.order("created_at DESC")
		
	end

	def new
		@post = Post.new
		
		
	end

	def create
		
		@post = Post.new(post_params)
		
    	if @post.save
	      	flash[:notice] = "OK"
	     	redirect_to post_path(@post)
	 	else
	 		render :new
	 	end
    end

	def show
		
		
	end				

	def edit
		
		
	end

	def update
		
		if @post.update(post_params)
		 flash[:notice] = "OK"
		redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		
		@post.destroy
		 flash[:notice] = "OK"
		redirect_to posts_path
	end

	
	
private
	def find_post
		@post = Post.find(params[:id])
		
	end
	def post_params
		params.require(:post).permit(:title, :body)
		
	end

	

	

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  

      private
        def sign_up_params
          params.require(:user).permit(
            :email, 
            :password, 
            :password_confirmation,
            :username,
            :firstname,
            :lastname
            
            )
        end
        def account_update_params
          params.require(:user).permit(
            :email, 
            :password, 
            :password_confirmation, 
            :current_password,
            :username,
            :firstname,
            :lastname
            
            )
        end 
        
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		
		<strong>
			Placed by : <%=comment.name %>
		</strong>
	
		
	</div>

	<div class="panel-body">
		
			<p><strong> >> : </strong><%=comment.body %></p>
			
			
	
		<p>
			<%= link_to 'Delete', [comment.post, comment], method: :delete, data: {confirm: "SURE ??? Delete comment ???"} %>
		</p>
	</div>
	
</div>

app/views/layouts/_foot.html.erb
<% if current_user %>

<footer style="border-top: 10px solid #292c2f;"">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>

    </footer>

<% else %>

    <footer style="background-color: #292c2f;
    box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
      font: bold 16px sans-serif;">

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
                </div>
            </div>
        </div>

    </footer>

<% end %>

app/views/layouts/_nav.html.erb
_nav.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theblaog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	    

  <!-- Custom Fonts 
  <link href="../font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css">-->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- End Custom Fonts -->
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                
                <%= link_to "Blogblog", root_path, class:"navbar-brand" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">

                    
                    <li><%= link_to "About", about_path %></li>

                    <!--<li><%= link_to "Sign Up", new_user_registration_path if !current_user %></li> ZO KAN T OOK. MAAR DONT REPEAT YOURSELF -->

                    <% if !current_user %>

                        <li><%= link_to "Sign Up", new_user_registration_path %></li> 
                        <li><%= link_to "Sign In", new_user_session_path %></li>
                    <% else %>
                        <li class="dropdown">

                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>

                              <ul class="dropdown-menu">
                                <li><%= link_to "New Post", new_post_path %></li>

                                    <li role="separator" class="divider"></li>

                                <li> <%= link_to "Edit Profile", edit_user_registration_path %> </li>

                                    <li role="separator" class="divider"></li>

                                <li> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </li>
                              </ul>

                         </li>

                    <% end %> 

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<!-- End Navigation -->
    
	<% if flash[:notice] %>
		<!--<div class="notice"><%= flash[:notice] %></div>-->
        
	<% end %>
<!-- <%= bootstrap_flash %> GEPL IN SHOW PAGE .!!!. EN IS NU IN IEDERE PAG ZICHTB ALS NODIG  UNDER HEADER-->
	<%= yield %>

<!-- Footer -->
   

<%= render 'layouts/foot' %>
</body>
</html>

app/views/pages/about.html.erb
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header4">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">

                        <h1>About Me</h1>
						
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>

                    </div>
                </div>
            </div>
        </div>

    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
                <div style="width:250px;">
					<%= image_tag("plaatje2.png", alt: "bla paarsefoto", width:"100%") %>
				</div>
				
            </div>
        </div>
    </div>

    <hr>
<%= link_to("About", controller: :pages, action: :about) %>
<%= link_to("Contact", controller: :pages, action: :contact) %>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<a href="about">About</a>
<a href="contact">Contact</a>

<%= link_to("About", controller: :pages, action: :about) %>
<%= link_to("Contact", controller: :pages, action: :contact) %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>

	<% if @post.errors.any? %>
		<ul>
			<% @post.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>	
	<% end %>

    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <%= f.label :title %>
            <h2>title</h2>
            <p><%= f.text_field :title, class:"form-control", placeholder:"Min 5" %></p>

            <p class="help-block text-danger"></p>
        </div>
    </div>
    
   
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
        <p><%= f.label :body %></p>
        <h2>Your Post</h2>
            <p><%= f.text_area :body, class:"form-control", placeholder:"Min 20 Caracters"%></p>
            
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <br>
    <div id="success"></div>
    <div class="row">
        <div class="form-group col-xs-12">
            
            <%= f.submit class:"btn btn-default"%>
        </div>
    </div>

<% end %>                    

app/views/posts/edit.html.erb
 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header2">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><%= @post.title %></h1>
                        
                        <span class="meta"><%= link_to 'Back', post_path(@post) %> | <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "SURE ??? Delete ???"} %></span>
                    </div>
                </div>
            </div>
        </div>
    </header>

 <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                   <%= render "form" %>
                </div>
            </div>
        </div>
    </article>

<h2>Edit Post nr : <%= params[:id] %> | <%= link_to 'Back', posts_path %></h2>


  

	

app/views/posts/index.html.erb
 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>SIT back & BLOG</h1>
                        <hr class="small">
                        <span class="subheading">Forget About All , JUST BLOG</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
	<%= bootstrap_flash %>
	<div class="container">
	<h1><%= link_to 'New Post', new_post_path %></h1>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

            	<% @posts.each do |post| %>
	            	<div class="post-preview">
	                    
                         <h2 class="post-title">
                            <%= link_to post.title, post_path(post) %>
                         </h2>

                    
                         
	                     <p><%= truncate(post.body) %></p>

	                     <p class="post-meta">
	                    	<%= link_to 'Edit', edit_post_path(post) %> | <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: "SURE ??? Delete ???"} %>
	                    </p>
	                </div>
                <% end %>

                <hr>
            </div>
        </div>
    </div>

app/views/posts/new.html.erb
 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header3">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Create New post</h1>

                        <hr class="small">
                        <span class="subheading">Have An Idea or Article ? There's A Nice Form Below , <strong>Use It</strong> .</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
	
	 <div class="lightbg" style="background-color:#f9f7f7;">
	    <div class="container">
	        <div class="row">
	            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

					<%= render "form" %>

	            </div>
	        </div>
	    </div>
	</div>

<h1><%= link_to "BACK", posts_path %></h1>


  

app/views/posts/show.html.erb
 <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header header2">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1><%= @post.title %></h1>
                        
                        <span class="meta"><%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: "SURE ??? Delete ???"} %></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
<%= bootstrap_flash %>
 <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                
                    <p><%= @post.body %></p>
					<% if @post.comments.count > 0 %>
	                    <hr />
							<h3>All Comments:</h3>
	                    <hr />

	                    <%= render @post.comments.order("created_at DESC") %>
                    <% end %>
                </div>
            </div>
        </div>
    </article>

    <small><%= params[:id] %> <%= link_to 'Back', posts_path %></small>
 <!-- Form -->
    <div class="lightbg" style="background-color:lightgreen;">
	    <div class="container">
	        <div class="row">
	            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
	               <h3>Comment Something</h3>
	                <%= form_for [@post, @post.comments.build] do |f| %>
	                    <div class="row control-group">
	                        <div class="form-group col-xs-12 floating-label-form-group controls">
	                            <label>Name</label>
	                            <%= f.text_field :name, class:"form-control", placeholder:"Name"%>
	                            
	                        </div>
	                    </div>
	                    
	                    
	                    <div class="row control-group">
	                        <div class="form-group col-xs-12 floating-label-form-group controls">

	                            <%= f.text_area :body, class:"form-control", placeholder:"Your Comment", id:"message" %>
	                            
	                        </div>
	                    </div>
	                    <br>
	                    <div id="success"></div>
	                    <div class="row">
	                        <div class="form-group col-xs-12">
	                        	<%= f.submit class:"btn btn-default"%>
	                            
	                        </div>
	                    </div>
	                <% end %>
	            </div>
	        </div>
	    </div>
	</div>